# This is like a dictionary where base, data_source, split, process, model and train are different dictionaries
base:
  # key and value
  # key is parameter and value is it's value
  # projects : name
  projects: dvc_pipeline_with_iris
  random_state: 42
  target_col: species

data_source:
  data_path: data/iris.csv

split:
  dir: data/split
  train_file: train.csv
  test_file: test.csv
  split_ratio: 0.20

process:
  dir: data/processed
  train_file: train.csv
  test_file: test.csv

train: 
  n_est: 2

model_dir: model